name: BankingSolution CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    #  Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    #  Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Match your project runtime

    #  Restore project dependencies
    - name: Restore dependencies
      run: dotnet restore

    #  Install dotnet-ef globally
    - name: Install EF Core CLI globally
      run: dotnet tool install --global dotnet-ef --version 9.0.8 || dotnet tool update --global dotnet-ef

    #  Add global tools folder to PATH
    - name: Add dotnet global tools to PATH
      shell: powershell
      run: |
        $env:PATH += ";$env:USERPROFILE\.dotnet\tools"
        echo "PATH updated: $env:PATH"

    #  Build the project
    - name: Build project
      run: dotnet build --no-restore

    # Update database using EF Core
    - name: Update database
      run: dotnet ef database update --project src/Banking.Infrastructure
