name: BankingSolution CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Optional: enable services for integration tests
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: > 
          --bind_ip_all
          --quiet
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: > 
          --env RABBITMQ_DEFAULT_USER=guest
          --env RABBITMQ_DEFAULT_PASS=guest

    env:
      MONGODB_CONNECTION: mongodb://localhost:27017
      RABBITMQ_CONNECTION: amqp://guest:guest@localhost:5672/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test ./tests --no-build --configuration Release --filter "Category=Unit" --verbosity normal

      # Optional: Run integration tests against Mongo & RabbitMQ
      - name: Run integration tests
        if: success()
        run: dotnet test ./tests --no-build --configuration Release --filter "Category=Integration" --verbosity normal
